---
title: "Preliminary Crosstabs"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(knitr)
library(readr)
library(dplyr)
library(tidyr)
library(tidyverse)
library(gt)
library(gtExtras)
library(webshot)
```


```{r, warning=FALSE, message=FALSE, echo=FALSE}
#YOU'LL NEED TO UPDATE THIS TO WHERE YOU SAVE THE DATA
data_path<-"C:/Users/turitto/Documents/GitHub/mdsenatepoll/prelim_crosstabs/data/prelim"

setwd(data_path)

responses<-read.csv("responses.csv")%>%
  mutate(generation = case_when(
    birthyr < 1928 ~ "Greatest",
    birthyr >= 1928 & birthyr < 1946 ~ "Silent Gen",
    birthyr >= 1946 & birthyr < 1965 ~ "Baby Boomer",
    birthyr >= 1965 & birthyr < 1981 ~ "Gen X",
    birthyr >= 1981 & birthyr < 1997 ~ "Millennial",
    birthyr >= 1997 ~ "Gen Z"
  ))%>%
  mutate(educ=ifelse(educ=="2-year","2-year degree",educ))%>%
  mutate(educ=ifelse(educ=="4-year","4-year degree",educ))%>%
  mutate(Question14_other=ifelse(Question14_other=="__NA__","not selected","other specified"))%>%
  mutate(Question20=as.numeric(Question20),
         Question21=as.numeric(Question21),
         Question24=as.numeric(Question24),
         )

variables<-read.csv("variable_codebook.csv")

questions<-c(
  "Question1", "Question2", "Question3", "q4", "q5", "q6", "q7", "q8", "q9", "q10", 
  "q11", "q12", "q13", "Question14", "Question15", "Question16", "Question17", 
  "Question18", "Question19", "Question20", "Question21", "Question22_1", "Question22_2", "Question22_3", 
  "Question22_4", "Question22_5", "Question22_6", "Question22_7", "Question22_8", 
  "Question22_9", "Question22_99", "Question23", "Question24", "Question25a", "Question25b", "Question26_1", 
  "Question26_2", "Question26_3", "Question26_4", "Question26_5", "Question26_6", 
  "Question26_7", "Question26_8", "Question26_9", "Question26_10", "Question26_19", 
  "Question26_99", "Question27", "Question28", "Question29", "Question30"
)

question_types<-c(
  "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", 
  "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", 
  "categorical", "categorical", "categorical", "categorical", "categorical", "interval", "interval", 
  "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", 
  "categorical", "categorical", "categorical", "categorical", "interval", "categorical", "categorical", 
  "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", 
  "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", 
  "categorical", "categorical"
)

sort<-data.frame(
  Group = c("Total", "Democrat", "Independent", "Republican", "White", 
            "Black", "Asian", "Female", "Male", "High school graduate", 
            "Some college", "2-year degree", "4-year degree", "Post-grad", "Silent Gen", 
            "Baby Boomer", "Gen X", "Millennial", "Gen Z"),
  order = 1:19
)
```

```{r}

for (i in seq_along(questions)) {

  if (question_types[i] == "categorical") {
    
    total <- responses %>%
      group_by(!!sym(questions[i])) %>%
      summarise(Responses = paste0(round(100 * n() / nrow(responses), 1), "%")) %>%
      pivot_wider(names_from = !!sym(questions[i]), values_from = Responses) %>%
      mutate(Group = "Total")
  
  pid3 <- responses %>%
    group_by(pid3, !!sym(questions[i])) %>%
    summarise(n = n(), .groups = 'drop') %>%
    group_by(pid3) %>%
    mutate(Responses = paste0(round(n / sum(n) * 100,1),"%"))%>%
    select(-n)%>%
    pivot_wider(names_from = !!sym(questions[i]), values_from = Responses) %>%
    rename(Group = pid3)
  
  race <- responses %>%
    group_by(race, !!sym(questions[i])) %>%
    summarise(n = n(), .groups = 'drop') %>%
    group_by(race) %>%
    mutate(Responses = paste0(round(n / sum(n) * 100,1),"%"))%>%
    select(-n)%>%
    pivot_wider(names_from = !!sym(questions[i]), values_from = Responses) %>%
    rename(Group = race)
  
  gender <- responses %>%
    group_by(gender, !!sym(questions[i])) %>%
    summarise(n = n(), .groups = 'drop') %>%
    group_by(gender) %>%
    mutate(Responses = paste0(round(n / sum(n) * 100,1),"%"))%>%
    select(-n)%>%
    pivot_wider(names_from = !!sym(questions[i]), values_from = Responses) %>%
    rename(Group = gender)
  
  educ <- responses %>%
    group_by(educ, !!sym(questions[i])) %>%
    summarise(n = n(), .groups = 'drop') %>%
    group_by(educ) %>%
    mutate(Responses = paste0(round(n / sum(n) * 100,1),"%"))%>%
    select(-n)%>%
    pivot_wider(names_from = !!sym(questions[i]), values_from = Responses) %>%
    rename(Group = educ)
  
  generation <- responses %>%
    group_by(generation, !!sym(questions[i])) %>%
    summarise(n = n(), .groups = 'drop') %>%
    group_by(generation) %>%
    mutate(Responses = paste0(round(n / sum(n) * 100,1),"%"))%>%
    select(-n)%>%
    pivot_wider(names_from = !!sym(questions[i]), values_from = Responses) %>%
    rename(Group = generation)
  
  final <- bind_rows(total, pid3, race, gender, educ, generation) %>%
    left_join(sort,by=c("Group")) %>%
    arrange(order) %>%
    select(-order) %>%
    select(Group, everything())
  
    # print(
      gt_table<-gt(final) %>%
        tab_header(
          title = variables$question[variables$variable == questions[i]],
          subtitle = questions[i]
        ) %>%
        tab_style(
          style = list(
            cell_fill(color = "gray95")
          ),
          locations = cells_body(
            rows = seq(1, nrow(final), 2)
          )
        )
    # )
    
    gtsave(data=gt_table, filename=paste0(data_path,"/crosstab_",i,".html"))


  } else if (question_types[i] == "interval") {
    
    total_i<-responses%>%
      summarise(
        min = min(!!sym(questions[i]), na.rm = TRUE),
        p25 = quantile(!!sym(questions[i]), 0.25, na.rm = TRUE),
        median = median(!!sym(questions[i]), na.rm = TRUE),
        mean = mean(!!sym(questions[i]), na.rm = TRUE),
        p75 = quantile(!!sym(questions[i]), 0.75, na.rm = TRUE),
        max = max(!!sym(questions[i]), na.rm = TRUE)
      )%>%
    mutate(Group = "Total")
    
    pid3_i<-responses%>%
      group_by(pid3)%>%
      summarise(
        min = min(!!sym(questions[i]), na.rm = TRUE),
        p25 = quantile(!!sym(questions[i]), 0.25, na.rm = TRUE),
        median = median(!!sym(questions[i]), na.rm = TRUE),
        mean = mean(!!sym(questions[i]), na.rm = TRUE),
        p75 = quantile(!!sym(questions[i]), 0.75, na.rm = TRUE),
        max = max(!!sym(questions[i]), na.rm = TRUE)
      )%>%
    rename(Group = pid3)
      
    race_i<-responses%>%
      group_by(race)%>%
      summarise(
        min = min(!!sym(questions[i]), na.rm = TRUE),
        p25 = quantile(!!sym(questions[i]), 0.25, na.rm = TRUE),
        median = median(!!sym(questions[i]), na.rm = TRUE),
        mean = mean(!!sym(questions[i]), na.rm = TRUE),
        p75 = quantile(!!sym(questions[i]), 0.75, na.rm = TRUE),
        max = max(!!sym(questions[i]), na.rm = TRUE)
      )%>%
    rename(Group = race)

    gender_i<-responses%>%
      group_by(gender)%>%
      summarise(
        min = min(!!sym(questions[i]), na.rm = TRUE),
        p25 = quantile(!!sym(questions[i]), 0.25, na.rm = TRUE),
        median = median(!!sym(questions[i]), na.rm = TRUE),
        mean = mean(!!sym(questions[i]), na.rm = TRUE),
        p75 = quantile(!!sym(questions[i]), 0.75, na.rm = TRUE),
        max = max(!!sym(questions[i]), na.rm = TRUE)
      )%>%
    rename(Group = gender)

     educ_i<-responses%>%
      group_by(educ)%>%
      summarise(
        min = min(!!sym(questions[i]), na.rm = TRUE),
        p25 = quantile(!!sym(questions[i]), 0.25, na.rm = TRUE),
        median = median(!!sym(questions[i]), na.rm = TRUE),
        mean = mean(!!sym(questions[i]), na.rm = TRUE),
        p75 = quantile(!!sym(questions[i]), 0.75, na.rm = TRUE),
        max = max(!!sym(questions[i]), na.rm = TRUE)
      )%>%
    rename(Group = educ)

    generation_i<-responses%>%
      group_by(generation)%>%
      summarise(
        min = min(!!sym(questions[i]), na.rm = TRUE),
        p25 = quantile(!!sym(questions[i]), 0.25, na.rm = TRUE),
        median = median(!!sym(questions[i]), na.rm = TRUE),
        mean = mean(!!sym(questions[i]), na.rm = TRUE),
        p75 = quantile(!!sym(questions[i]), 0.75, na.rm = TRUE),
        max = max(!!sym(questions[i]), na.rm = TRUE)
      )%>%
    rename(Group = generation)
    
  final_i <- bind_rows(total_i, pid3_i, race_i, gender_i, educ_i, generation_i) %>%
    mutate(min=round(min,1),
           p25=round(p25,1),
           median=round(median,1),
           mean=round(mean,1),
           p75=round(p75,1),
           max=round(max,1),
           )%>%
    left_join(sort, by=c("Group")) %>%
    arrange(order) %>%
    select(-order) %>%
    select(Group, everything())
  
    # print(
      gt_table<-gt(final_i) %>%
        tab_header(
          title = variables$question[variables$variable == questions[i]],
          subtitle = questions[i]
        ) %>%
        tab_style(
          style = list(
            cell_fill(color = "gray95")
          ),
          locations = cells_body(
            rows = seq(1, nrow(final), 2)
          )
        )
    # )
    
    gtsave(data=gt_table, filename=paste0(data_path,"/crosstab_",i,".html"))


   }

}

```